#!/usr/bin/env bash

export LD_LIBRARY_PATH=$(pwd)/lib/aarch64-linux-gnu:$(pwd)/lib
export QTWEBENGINEPROCESS_PATH=$(pwd)/lib/aarch64-linux-gnu/bin/QtWebEngineProcess
export QTWEBENGINE_RESOURCES_PATH=$(pwd)/lib/aarch64-linux-gnu/resources
export QT_PLUGIN_PATH=$(pwd)/lib/aarch64-linux-gnu/qt6/plugins
export QML_IMPORT_PATH=$(pwd)/lib/aarch64-linux-gnu/qt6/qml:$(pwd)/usr/lib/aarch64-linux-gnu/qt6/qml:$(pwd)/lib/aarch64-linux-gnu
export QT_IM_MODULE=maliit
export QT_OPENGL_VARIANT=gles
export LOMIRI_UI_TOOLKIT_THEMES_PATH=$(pwd)/lib/aarch64-linux-gnu/qt6/qml
unset QT_QUICK_CONTROLS_STYLE
export QT_QPA_PLATFORM=wayland-egl
export QT_SCALE_FACTOR=$(awk 'BEGIN {printf "%.1f\n", 24/9}')

exec "$@"
