name: Clickable Build

on:
  # start the script when code is pushed to main branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        arch: [amd64, arm64, armhf]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # here @latest doesn't work, specific version v4 or above
        with:
          submodules: 'true'
      - name: Parse version
        run: |
          echo ARTIFACT_VERSION=$(cat prebuild.sh | grep "export REPO_VERSION=" | awk -F'"' '$0=$2')$(cat prebuild.sh | grep "export CLICK_VERSION_PREFIX=" | awk -F'"' '$0=$2') >> $GITHUB_ENV
      - name: Install clickable
        run: |
          python3 -m pip install clickable-ut
      - name: Build
        # build the app with clickable for all specified architectures
        run: |
          clickable build --arch ${{ matrix.arch }}
      - name: Upload Artifacts
        # upload the build artifacts to github using the appname and version
        uses: actions/upload-artifact@v4 # here @latest doesn't work, specific version v4 or above
        with:
          name: cinny.danfro_${{ env.ARTIFACT_VERSION }}_${{ matrix.arch }}.zip
          path: build/*/app/*.click
          if-no-files-found: error
