# this file will build the app, create a downloadable artifact, publish the app to OpenStore and create a release with the build app as asset

name: build and github release

on:
  # start the script when a tag is pushed ending with RC (no underline before RC, that will fail linting)
  # tag format: v1.2.3.4RC
  # note: GitHub Actions does not support full regex in tag patterns; it uses simple glob patterns like *, ?, and [] instead.
  # https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
  push:
    tags:
      - 'v*.*.*.*RC'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

# define the build job
jobs:
  build:
    strategy:
      matrix:
        arch: [amd64, arm64, armhf]
        appname: [cinny.danfro]
    runs-on: ubuntu-latest
    container:
      image: clickable/ci-ut24.04-1.x-${{ matrix.arch }}
    steps:
      - name: Checkout
        # https://github.com/actions/checkout
        uses: actions/checkout@v6 # here @latest doesn't work, specific version v6 or above
        with:
          submodules: 'true'
      - name: Fix git dubious ownership
        run:  >-
          git status
          || git config --system --add safe.directory "$GITHUB_WORKSPACE"
      - name: Extract NVM version from prebuild.sh
        id: extract-nvm-version
        run: echo "NVM_VERSION=$(grep -oP '(?<=NVM_VERSION=)[^ ]+' prebuild.sh)" >> $GITHUB_ENV
      - name: Extract node version from prebuild.sh
        id: extract-node-version
        run: echo "NODE_VERSION=$(grep -oP '(?<=NODE_VERSION=)[^ ]+' prebuild.sh)" >> $GITHUB_ENV
      - name: Set up Node.js environment
        run: |
          export NVM_DIR="$HOME/.nvm"
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v$NVM_VERSION/install.sh | bash
          . "$NVM_DIR/nvm.sh"  # Source nvm
          nvm install $NODE_VERSION
          nvm use $NODE_VERSION
          echo "Node.js $(node -v) installed via nvm"
      - name: Set Artifact Version
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          ARTIFACT_VERSION=${TAG_NAME#v}
          echo "ARTIFACT_VERSION=$ARTIFACT_VERSION" >> $GITHUB_ENV
          echo "Set ARTIFACT_VERSION=$ARTIFACT_VERSION"
      - name: Debug ARTIFACT_VERSION
        run: echo "ARTIFACT_VERSION=$ARTIFACT_VERSION"
        env:
          ARTIFACT_VERSION: ${{ env.ARTIFACT_VERSION }}
      - name: Build
        # build the app with clickable for all specified architectures
        run: |
          clickable build --arch ${{ matrix.arch }}
      - name: Upload artifacts
        # upload the build artifacts to github using the appname and version
        # https://github.com/actions/upload-artifact
        uses: actions/upload-artifact@v7 # here @latest doesn't work, specific version v4 or above
        with:
          name: ${{ matrix.appname }}_${{ matrix.arch }}
          # name: cinny.danfro_${{ env.ARTIFACT_VERSION }}_${{ matrix.arch }}.zip
          path: build/*/app/*.click
          if-no-files-found: error
          archive: false
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: softprops/action-gh-release@v3 # https://github.com/softprops/action-gh-release
        with:
          files: build/*/app/*.click
          body: "${{ github.event.head_commit.message }}" # Grab the last commit message as changelog
          prerelease: true